#165413099 intergrate jwt
andela/riders-ah-backend pull request #11
Opened 2019-04-30 18:03 UTC by ericnyirimana

Description
=======
Every system application needs authentication to permit users to access their information. With this PR I have integrated JWT( JSON WebToken ) for generating a token made of encrypted user information for session checking and privileges.

Type of change
=======
N/A

How has it been tested
=======
It is tested when you signup via ```api/auth/signup```

Checklist:
=======
N/A

Pivotal tracker story ID
=======
[165413099](https://www.pivotaltracker.com/n/projects/2326984/stories/165413099)

2019-04-30 21:18 UTC, Kabalisa commented on helpers/index.js
> +export default Helper;
Add a new line

2019-04-30 21:19 UTC, Kabalisa commented on routes/user.route.js
> +export default router;
also add a new line here

2019-04-30 21:21 UTC, Kabalisa commented on controllers/user.controller.js
> +export default addUser;
add a new line here

2019-05-02 20:28 UTC, Kabalisa approved these changes
@ericnyirimana Good job. please update your PR as it currently has conflicts with develop.

2019-05-03 08:29 UTC, Niyitangasam approved these changes

2019-05-03 10:12 UTC, macphilips requested changes

2019-05-03 10:12 UTC, macphilips commented on tests/user.test.js
> +            expect(res.body.data.username).to.be.equal(user.username);
```suggestion
            expect(res.body.data.username).to.be.equal(user.username);
            expect(res.body.data.password).to.be.equal(undefined);
```

2019-05-03 11:00 UTC, macphilips requested changes

2019-05-03 11:00 UTC, macphilips commented on package.json
> +    "test": "NODE_ENV=test npm run migrate && NODE_ENV=test  nyc mocha --require @babel/register --require @babel/polyfill \"tests/**/*.js\"",
```suggestion
     "pretest": "npm run lint:fix && NODE_ENV=test npm run migrate && NODE_ENV=test",
    "test": "NODE_ENV=test  nyc mocha --require @babel/register --require @babel/polyfill \"tests/**/*.js\"",
```

2019-05-06 13:38 UTC, merged