#165413104 Enable Social Login via Google, Facebook and twitter
andela/riders-ah-backend pull request #13
Opened 2019-04-30 23:37 UTC by Niyitangasam

Description
=======
This PR implements login functionalities with pre-existing social media accounts. Login strategies for facebook, twitter and google are implemented. It also adds the functionality of keeping users info in case they will use the system next time

Type of change
=======
N/A

How has it been tested
=======
It can be tested through below links

- ```api/login/google```
- ```api/login/facebook```
- ```api/login/twitter```

Checklist:
=======
N/A

Pivotal tracker story ID
=======
[165413099](https://www.pivotaltracker.com/n/projects/2326984/stories/165413104)

2019-05-02 07:11 UTC, AJAkimana commented on controllers/user.controller.js
> +import db from '../models/index';
User `import { User } from '../models' ` instead of `import db from '../models/index'`, for more readable code

2019-05-02 07:34 UTC, AJAkimana reviewed
Good work man, but I would suggest using sequelize functions instead to create the other function that requires sequelize functions. For instance the function `findRecord` I think it is not needed.

2019-05-02 09:55 UTC, macphilips commented on controllers/index.js
> +
Kindly remove this line since there is no significant change in this file

2019-05-02 14:23 UTC, jabichris approved these changes

2019-05-02 20:49 UTC, Kabalisa approved these changes

2019-05-02 20:50 UTC, Kabalisa approved these changes

2019-05-03 07:54 UTC, AJAkimana approved these changes

2019-05-03 11:01 UTC, macphilips requested changes

2019-05-03 11:01 UTC, macphilips commented on helpers/passport.js
> +    console.log(accessToken);
remove `console.log`

2019-05-03 11:01 UTC, macphilips commented on package.json
>      "start:dev": "nodemon --exec babel-node index.js",
```suggestion
    "start:dev": "nodemon --exec node --require @babel/register --require dotenv/config index.js",
```

2019-05-06 09:57 UTC, macphilips requested changes

2019-05-06 09:57 UTC, macphilips commented on config/passport/index.js
> +/* eslint-disable require-jsdoc */
Remove this comment

2019-05-06 10:02 UTC, macphilips commented on helpers/index.js
> +/* eslint-disable require-jsdoc */
Remove comment

2019-05-06 10:33 UTC, merged