#165413105 user profile
andela/riders-ah-backend pull request #15
Opened 2019-05-02 10:28 UTC by jabichris

#### Description

This PR implements user profile functionalities, like editing username, bio or image. It allows also the user to view other users profiles.
#### Type of change

N/A
#### How has it been tested

It can be tested using the following link api/users/: id and use GET or PUT method in postman
#### Checklist:

N/A
#### Pivotal tracker story ID
https://www.pivotaltracker.com/story/show/165413105

2019-05-03 07:32 UTC, Kabalisa approved these changes
@jabichris Good work. remove the conflicts now.

2019-05-06 08:44 UTC, Niyitangasam approved these changes

2019-05-06 10:26 UTC, macphilips commented on tests/profile.js
> +        email: 'jabichris@gmail.com',
Remove your email and put a dummy email there

2019-05-09 12:05 UTC, macphilips requested changes

2019-05-09 12:05 UTC, macphilips commented on tests/profile.js
> +        expect(res.body.data).to.have.property('password');
```suggestion
        expect(res.body.data).not.to.have.property('password');
```

2019-05-09 12:05 UTC, macphilips commented on routes/api/index.js
> +router.use('/users', users);
```suggestion
router.use('/users', users, resetPassword);
```

2019-05-09 12:05 UTC, macphilips commented on routes/api/index.js
>  router.use('/user', resetPassword);
```suggestion

```

2019-05-09 12:06 UTC, macphilips commented on controllers/profile.js
> +// import { now } from 'sequelize/types/lib/utils';
remove comment

2019-05-09 12:43 UTC, merged