#165413108 fetch all ratings related to an article
andela/riders-ah-backend pull request #37
Opened 2019-05-20 14:12 UTC by ericnyirimana

Description
=======
Author heaven an application where writers can publish their articles and also get feedback on the quality of their post. This feature permits users to view given ratings on a particular article.

Type of change
=======
N/A

How has it been tested
=======
- It is tested using a GET method via this URL path ```api/v1/articles/<article-slug>/rate```

Checklist:
=======
N/A

Pivotal tracker story ID
=======
[165413108](https://www.pivotaltracker.com/n/projects/2326984/stories/165413108)

2019-05-20 14:37 UTC, AJAkimana requested changes
Good job @ericnyirimana, Before fetching rates check if the article does exist

2019-05-21 06:39 UTC, AJAkimana approved these changes
Great work

2019-05-21 08:44 UTC, Niyitangasam approved these changes

2019-05-21 13:27 UTC, denislohan commented
implement i this is a chore:
 we are fetching **ratings** not **rate**

2019-05-21 13:27 UTC, merged