Setup Travis CI for management service
andela/riders-ah-backend pull request #4
Opened 2019-04-24 15:26 UTC by AJAkimana

#### Description
Stable CI setup will make it easy to integrate our code while ensuring that all defined tests are passing per integration.
#### Type of change
N/A
#### How Has This Been Tested?
N/A
#### Acceptance Criteria:
Working CI integration with Travis CI.
#### Checklist:
N/A
#### PIVOTAL TRACKER
#165413090

2019-04-24 15:58 UTC, ericnyirimana reviewed
You have set up well TravisCI. The remain thing is to merge with @jabichris test so that the test can be built successfully.

2019-04-24 16:00 UTC, Kabalisa commented
@AJAkimana Travis is configured well but the Acceptance Criteria title in your PR is not included in the format of how to write a PR in the engineering playbook.

2019-04-24 16:02 UTC, Kabalisa requested changes
@AJAkimana Travis is configured well but the Acceptance Criteria title in your PR is not included in the format of how to write a PR in the engineering playbook.

2019-04-25 08:30 UTC, AJAkimana commented
> @AJAkimana Travis is configured well but the Acceptance Criteria title in your PR is not included in the format of how to write a PR in the engineering playbook.

Ok I have edited it

2019-04-25 08:46 UTC, jabichris reviewed
You need tests.

2019-04-25 10:52 UTC, macphilips requested changes

2019-04-25 10:52 UTC, macphilips commented on .travis.yml
> +
remove extra new line

2019-04-25 11:06 UTC, AJAkimana commented on .travis.yml
> +
> remove extra new line

I removed it

2019-04-25 11:35 UTC, macphilips commented on .travis.yml
> +
I can still see it here

2019-04-25 19:10 UTC, AJAkimana commented on .travis.yml
> +
I did correct it. Check it again

2019-04-26 09:48 UTC, merged