chore(auth): Sending verification email after creating account
andela/riders-ah-backend pull request #42
Opened 2019-05-21 18:33 UTC by AJAkimana

#### Description
This PR is about to send a verification email with a link to verify it. User should be able to receive a verification link via email upon successful signup

#### Type of change
N/A

#### How Has This Been Tested?
It can be tested by visiting this route `/users/verification?token={user-token}&email={user-email}`

#### Checklist:
N/A

#### Pivotal tracker story ID
[#166154667](https://www.pivotaltracker.com/n/projects/2326984/stories/166154667)

2019-05-23 07:45 UTC, Niyitangasam requested changes
Great work although  I would suggest changing your implementation and allow a user to log in when the email is not verified and send information in a token that will help us to inform the user that they must verify their account.
Also, you can consider adding the option of resending a verification email.

2019-05-23 08:00 UTC, Niyitangasam commented on controllers/user.controller.js
> +          html: `<html>You have created an account to the Author Heaven. Click to <a href='${link}'><strong>this link</strong></a> to validate your account`
I would suggest to refactor this code and create a function that will help us to send a verification email because we will need this functionality not only here. We will need it when a Superadmin create a user or when a user needs us to resent a verification email

2019-05-23 08:30 UTC, AJAkimana commented
> Great work although I would suggest changing your implementation and allow a user to log in when the email is not verified and send information in a token that will help us to inform the user that they must verify their account.
> Also, you can consider adding the option of resending a verification email.

Thanks for the comment, but remember if we are allowing the user to write something into a system, we have to make sure that is not a robot, this is the reason for email verification

2019-05-24 15:05 UTC, Niyitangasam approved these changes

2019-05-24 15:05 UTC, ericnyirimana approved these changes

2019-05-24 15:18 UTC, merged