Integrate with coveralls
andela/riders-ah-backend pull request #6
Opened 2019-04-25 08:22 UTC by AJAkimana

Description
=======
This is to ensure we are properly informed just how well our code base is tested which in turn provides quality assurance for the product

Type of change
=======
N/A

How has it been tested
=======
N/A

Checklist:
=======
N/A

Pivotal tracker story ID
=======
[#165413096](https://www.pivotaltracker.com/n/projects/2326984/stories/165413096)

2019-04-25 10:14 UTC, macphilips requested changes

2019-04-25 10:14 UTC, macphilips commented on .babelrc
> +}
Add new line

2019-04-26 14:24 UTC, macphilips requested changes

2019-04-26 14:24 UTC, macphilips commented on package.json
> +    "migrate": "",
Remove this line. it's of no use

2019-04-27 11:47 UTC, Niyitangasam requested changes
I am not able to run this locally.
![image](https://user-images.githubusercontent.com/12936280/56849275-d1a2ea00-68f2-11e9-8c9f-c810240e61d7.png)

2019-04-28 19:42 UTC, Niyitangasam approved these changes

2019-04-28 21:15 UTC, AJAkimana commented on .babelrc
> +}
> Add new line

:all-done

2019-04-28 21:18 UTC, AJAkimana commented on package.json
> +    "migrate": "",
> Remove this line. it's of no use
I am On it

2019-04-29 11:07 UTC, AJAkimana commented on package.json
> +    "migrate": "",
> Remove this line. it's of no use
it's done

2019-04-29 11:16 UTC, ericnyirimana approved these changes
It works great, good work

2019-05-02 11:40 UTC, macphilips requested changes

2019-05-02 11:40 UTC, macphilips commented on .gitignore
> +package-lock.json
We already have package-lock.json defined in this file kindly remove this

2019-05-02 11:40 UTC, macphilips commented on .gitignore
> +.env
We already have .env defined in this file kindly remove this

2019-05-02 13:45 UTC, merged