#165413091 configure PostgreSQL as a db engine
andela/riders-ah-backend pull request #8
Opened 2019-04-26 08:03 UTC by Kabalisa

#### Description
In our authors' haven project we are going to be working with a lot of data and that is why we need to configure a database to persist our data into. our database is going to be configured to use PostgreSQL as its DB engine and sequelize as an ORM.
#### Type of change
N/A
#### How Has This Been Tested?
* First, create two databases for the development environment and the test environment.
* run ```npm start``` to first migrate the table models available into your development database and then start the server.
* run ```npm run migrate``` to migrate available table models into your development database without starting the server.
* run ```npm run testmigration```   to migrate available table models into your test database without starting the server.
#### Checklist:
N/A
#### Pivotal Tracker ID
[#165413091](https://www.pivotaltracker.com/story/show/165413091)

2019-04-26 08:07 UTC, Niyitangasam commented on .babelrc
> +}
You can add a new line here

2019-04-26 08:09 UTC, Niyitangasam commented on .env
> +TESTDB_NAME=authorshaventest
You should have put .env in .gitignore

2019-04-26 08:09 UTC, Niyitangasam commented on .env
> +TESTDB_NAME=authorshaventest
Also, this code is not supposed to be pushed on github

2019-04-26 08:13 UTC, Niyitangasam commented on .sequelizerc
> +}
Please use ES6 syntax here

2019-04-26 08:14 UTC, Niyitangasam commented on index.js
> +export default app;
You can also rebase from develop branch because this index.js has changed

2019-04-26 08:18 UTC, Niyitangasam requested changes
You did a great Job, few things to change refer to  my inline comments.

2019-04-26 08:21 UTC, Niyitangasam commented on config/config.js
> +};
Use ES6 here as well

2019-04-26 08:40 UTC, AJAkimana commented
Great work Fiston. But remove .env file.

2019-04-26 08:42 UTC, AJAkimana requested changes
Remove .env file on repo

2019-04-26 14:53 UTC, macphilips commented on .sequelizerc
> +}
@Niyitangasam Sequeliize doesn't support es6

2019-04-26 15:17 UTC, macphilips requested changes
Nice work so far, but this is far from completion. I did not see any unit/integration test that tests the functionalities of your implementation. Also, attend to the comments I left below

2019-04-26 15:17 UTC, macphilips commented on migrations/20190425110658-create-users.js
> +        allowNull: false
We need to allow null for users `bio` so we will be able to register a new user. When creating a user on registration event the information we are getting from the user doesn't include `bio`.

2019-04-26 15:17 UTC, macphilips commented on models/users.js
> +  const users = sequelize.define('users', {
change the model name, it has to be in the singular form.
```suggestion
  const users = sequelize.define('User', {
```

2019-04-26 15:17 UTC, macphilips commented on config/config.js
> +        dialect: "postgres"
Make the dialect configurable
```suggestion
        dialect: process.env.DIALECT || "postgres"
```

2019-04-26 15:17 UTC, macphilips commented on config/config.js
> +        username: process.env.DB_USER,
change this configuration to use a database URL string rather provide a username, password, and database name. It too bulky to provide all this information via an environment variable.

2019-04-26 15:17 UTC, macphilips commented on config/config.js
> +};
Also, you might want to consider refactoring this file as it filled with duplicate fields

2019-04-26 15:17 UTC, macphilips commented on package.json
> +    "start": " ./node_modules/.bin/sequelize db:migrate && babel-node ./index.js",
```suggestion
    "start": " npm run migrate && babel-node ./index.js",
```

2019-04-26 20:00 UTC, Niyitangasam commented on .sequelizerc
> +}
@macphilips Thanks, I wasn't aware.

2019-04-27 08:03 UTC, Niyitangasam approved these changes

2019-04-27 11:54 UTC, Niyitangasam requested changes
Great Job, but you can add samples of db config in .env.sample file.

2019-04-27 21:20 UTC, Niyitangasam approved these changes

2019-04-28 21:07 UTC, AJAkimana approved these changes

2019-04-29 09:39 UTC, merged